# Generated by Django 4.2.5 on 2023-09-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ir_project', '0002_interview_podcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='interview/'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='podcast/'),
        ),
        migrations.AddField(
            model_name='region',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='region/'),
        ),
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='topic/'),
        ),
    ]
