# Generated by Django 4.2.5 on 2023-09-10 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ir_project', '0003_interview_image_podcast_image_region_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='interview_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='podcast',
            old_name='podcast_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='region_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='topic_slug',
            new_name='slug',
        ),
    ]
