# Generated by Django 4.2.5 on 2023-10-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ir_project', '0004_rename_interview_slug_interview_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('contact_sub', models.CharField(max_length=250)),
                ('contact_message', models.TextField()),
            ],
        ),
    ]
