# Generated by Django 4.2.5 on 2023-10-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ir_project', '0005_usercontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='usercontact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
