# Generated by Django 4.2.5 on 2023-09-26 10:48

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ir_project', '0004_rename_interview_slug_interview_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('image', models.ImageField(upload_to='article/')),
                ('status', models.IntegerField(default=0)),
                ('artice_content', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ir_project.topic')),
            ],
        ),
    ]
