# Generated by Django 4.2.5 on 2023-10-03 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ir_project', '0004_rename_interview_slug_interview_slug_and_more'),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicarticle',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ir_project.region'),
        ),
    ]
