# Generated by Django 4.2.5 on 2023-10-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_topicarticle_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicarticle',
            name='slug',
            field=models.SlugField(max_length=1000, unique=True),
        ),
    ]
