# Generated by Django 4.2.5 on 2023-10-03 23:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_topicarticle_create_by_topicarticle_writer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('image', models.ImageField(upload_to='event/')),
                ('cheaf_guest', models.CharField(max_length=250)),
                ('event_date', models.DateTimeField()),
                ('event_start', models.TimeField()),
                ('event_end', models.TimeField()),
                ('status', models.IntegerField(default=0)),
                ('guest_details_info', ckeditor.fields.RichTextField()),
                ('artice_content', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(max_length=1000, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
