# Generated by Django 4.2.5 on 2023-10-04 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='artice_content',
            new_name='event_content',
        ),
    ]
