# Generated by Django 4.2.5 on 2023-10-08 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_topicerror'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
